# Generated by Django 4.2.1 on 2023-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Title of the show"),
                ),
                (
                    "fav",
                    models.CharField(max_length=50, verbose_name="Favourite character"),
                ),
                ("rating", models.IntegerField(verbose_name="Rating for the show")),
                (
                    "image",
                    models.ImageField(
                        upload_to="shows_images", verbose_name="Image for the show"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Show",
        ),
    ]
