# Generated by Django 4.2.1 on 2023-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="image",
            field=models.ImageField(
                null=True, upload_to="show_images", verbose_name="Image of the show"
            ),
        ),
    ]
